### ISSUE TITLE
Dropdown in menu bar

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/e-editiones#14]
For SWT

**Comment by cyrill-martin** [comment]
@hanscools What would be the desired menu structure? I'm not sure how you envision to structure it. 
1. About
1. Ontologies
1. SWT
    - Semantic Web Technology
    - Ontology Modelling
    - Two-Step Formalization
1. Machine Reasoning
    - N3-Rule-Based Machine Reasoning
1. Literature

**Comment by hanscools** [comment]
1. About
2. Semantic Web Technology
- Introduction
- Advantages
3. Ontology
- Library (NIE-ontologies)
- Modeling
- Change/versioning
4. SPARQL
- Introduction (link to existing endpoints)
- Microservice (cf. inseri)
5. N3-Rule-Based Machine Reasoning
- Introduction
- N3-rules
- Microservice
6. Two-Step Formalization
7. Literature
