### ISSUE TITLE
Vermerken, dass man auch nach layout-aspekten suchen kann

### ISSUE THREAD

**Issue by janCstoffregen** [nie-ine/e-editiones#28]
bspw, suche den paragraph, der diese person enthält, und keine durchstreichungen

diese Suche geht uU bei anderen Tools nicht, SWT ermöglicht auch hier erforschbares

**Comment by janCstoffregen** [comment]
?

**Comment by janCstoffregen** [comment]
just a question...

**Comment by cyrill-martin** [comment]
Closed
