### ISSUE TITLE
Show q names only

### ISSUE THREAD

**Issue by cyrill-martin** [nie-ine/e-editiones#9]

**Comment by cyrill-martin** [comment]
[namespace]:[local-name]

rdfs:label
agent:Agent
etc.

**Comment by cyrill-martin** [comment]
Mostly done. 
It somehow still displays e.g. http://xmlns.com/foaf/0.1/Group, http://www.w3.org/2001/XMLSchema#date (???)

**Comment by hanscools** [comment]
Only those 2?

**Comment by cyrill-martin** [comment]
No, these are just examples. 
If something is a rdfs:subClassOf of http://xmlns.com/foaf/0.1/Agent, it doesn't show foaf:Agent but the complete IRI. It's somewhere in the if/else statements of the xsl file...

**Comment by hanscools** [comment]
Would it be possible in the XSL to use the prefix header and replace the namespace IRI with the prefix?

**Comment by cyrill-martin** [comment]
That's what the xsl does at other places and it's what I try to achieve but so far I haven't had any success :(

**Comment by hanscools** [comment]
Could it have st. to do with the ending of the namespace IRI: either slash or hash?

**Comment by cyrill-martin** [comment]
I found it. For any stupid reason the foaf namespace wasn't declared in the RDF/XML file I tested with. No worries, it's declared in the turtle file. If there's an error, it's somewhere else. Maybe I did some manual mistakes while testing.

**Comment by cyrill-martin** [comment]
Note to myself: 
Example agent.ttl:

When serializing to RDF, the foaf namespace is not declared as it isn't used in the RDF/XML. foaf is only used as an rdfs:resource, not as an actual XML element:  

<rdfs:subClassOf rdf:resource="http://xmlns.com/foaf/0.1/Agent"/>

Because the namespace isn't declared, the xslt doesn't replace http://xmlns.com/foaf/0.1/Agent with foaf:Agent.

**Comment by cyrill-martin** [comment]
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix cidoc: <http://www.cidoc-crm.org/cidoc-crm/>.
@prefix frbroo: <http://iflastandards.info/ns/fr/frbr/frbroo/>.

**Comment by cyrill-martin** [comment]
Done. 
If there's a prefix only, it will be show with the colon (e.g. agent: ). 
I look for foaf, cidoc, frbroo, and xsd IRIs.

**Comment by cyrill-martin** [comment]
At subclass, subproperty or other places, e.g. at
languages:iso639-3System concept:codingSystemHasDataType, and
calendar:hasJulianDayNumber rdfs:range :
the whole declaration of the object is given, instead of only the object q-name.

Can this be changed?

**Comment by cyrill-martin** [comment]
Won't do
